# En notebook for å lage clustre fra kollokasjoner

Ord kan dann clustre via en kollokasjonsanalyse. Her litt engelsk forklaring:

The term collocation has traditionally been restricted to words that are juxtaposed together as phrases like “strong coffee”, “strict regime” or “eat dinner”. Here we take collocations to be realized as skipgrams, or as word pairs that simply cooccur within a context which in itself is a contiguous sequence of words, typically a paragraph or a window of n words around a given word. Juxtaposed collocates will also be part of the result set. 

The collocates for W is the words that are associated with W based on a measure of association. The purpose of such a measure for a word W (e.g. “democracy”) is to provide a means of collecting associated words in the discourses in which W occurs within C. Collocations can be viewed as collecting discourse markers for W, in the sense that the collocates are uttered (written or spoken) together with W. The collocates for W are computed via an association measure on the set of all cooccurrent words.

Start med å importere de kommandoene som trengs fra nbtext

In [1]:
from module_update import update

Updated file nbtext.py
Updated file nbpictures.py

In [5]:
import nbtext as nb
from nbtext import cloud, get_urn, Cluster, Corpus
%matplotlib inline

In [6]:
words = 'min mitt mine'.split()
nb.collocation_data(words, yearfrom = 1800, yearto = 1780, limit = 1000, before = 1, after = 2, title = '%')

min

UnboundLocalError: local variable 'w' referenced before assignment

In [14]:
import pandas as pd
from nbtext import collocation

In [33]:
def collocation_data(words, yearfrom = 2000, yearto = 2005, limit = 1000, before = 5, after = 5, title = '%', corpus='bok'):
    """Collocation for a set of words sum up all the collocations words is a list of words or a blank separated string of words"""
    import sys
    a = dict()
    
    if isinstance(words, str):
        words = words.split()
    
    for word in words:
        
        print(word)
        try:
            
            a[word] = collocation(
                word, 
                yearfrom = yearfrom, yearto = yearto, limit = limit, 
                corpus = corpus, before = before, 
                after = after, title = title
            )
            
            a[word].columns = [word]
        
        except:    
            print(word, ' feilsituasjon', sys.exc_info())
    result = pd.DataFrame()
    for w in a:
        result = result.join(a[w], how='outer')
    return pd.DataFrame(result.sum(axis=1))

In [35]:
words = 'min mitt mine'.split()
frame = collocation_data(words, yearfrom = 2000, yearto = 2005, limit = 50, before = 1, after = 2, title = '%')

min
mitt
mine

In [36]:
frame

                  0
!              82.0
"              16.0
%               1.0
'               8.0
(              27.0
)              49.0
*               1.0
+               2.0
,             547.0
-              45.0
.             383.0
...            15.0
/              26.0
0               2.0
0.5             1.0
0.75            1.0
08              2.0
1              10.0
10             12.0
10,000          1.0
106             1.0
11              1.0
12              1.0
135             3.0
15             13.0
18              2.0
18.             1.0
180             2.0
1989.           1.0
2               6.0
...             ...
åssit           1.0
åt              1.0
ærbødige        1.0
ærend           1.0
ærer            1.0
öfver           1.0
øienbryn        1.0
øjne            1.0
økte            1.0
ønske           6.0
ønsker          1.0
øre             2.0
ørene           5.0
ører            3.0
øret            5.0
øversåttning    1.0
øvrige          1.0
øye             3.0
øyenbryn        1.0
øyet            1.0
øyne            6.0
øynene          4.0
øyner           1.0
čuodjá          1.0
—               1.0
’               1.0
“               1.0
”               2.0
•               1.0
■               1.0

[2713 rows x 1 columns]